[[EpollShim]]
arch = "aarch64"
git-tree-sha1 = "d52d7b855ddfcc4630cea818bdd0327a0c66cc14"
os = "freebsd"

    [[EpollShim.download]]
    sha256 = "9d04f40cc9ceec88f8f38492488134999817838466c52bae167efbe8845a65fb"
    url = "https://github.com/JuliaBinaryWrappers/EpollShim_jll.jl/releases/download/EpollShim-v0.0.20230411+1/EpollShim.v0.0.20230411.aarch64-unknown-freebsd.tar.gz"
[[EpollShim]]
arch = "x86_64"
git-tree-sha1 = "932046a060fcbffaa8a52a1bd14fe412b77c4cea"
os = "freebsd"

    [[EpollShim.download]]
    sha256 = "6b061328ebef8b29b3d20e3d017af4ec223d84720a7ba9608d6180d50f8fed83"
    url = "https://github.com/JuliaBinaryWrappers/EpollShim_jll.jl/releases/download/EpollShim-v0.0.20230411+1/EpollShim.v0.0.20230411.x86_64-unknown-freebsd.tar.gz"
